# Generated by Django 5.2.1 on 2025-05-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='search_count',
            field=models.BigIntegerField(default=1, verbose_name='Кол-во запросов'),
        ),
    ]
